version: "3.8"

services:
  #app:
  #  image: gregomebije/rubimoni-api:latest
  #  build: .
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - postgres
  #    - redis
  #  restart: always
  #  environment:
  #    SPRING_PROFILES_ACTIVE: prod
  #    DB_URL: jdbc:postgresql://postgres:5432/rubimoni
  #    DB_USER: postgres 
  #    DB_PASSWORD: ${DB_PASS}
  #    REDIS_HOST: redis
  #    REDIS_PORT: 6379
  
  postgres:
    image: postgres:16-alpine
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: double_entry_ledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #restart: always

  redis:
    image: redis:7-alpine
    container_name: dev-redis
    #restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:

